services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_MEMORY_LIMIT_MB: "1024" # Limit memory usage for Raspberry PI
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "if ! timeout 10 bash -c '</dev/tcp/localhost/1433'; then exit 1; fi"]
      interval: 15s
      retries: 20
      start_period: 180s
      timeout: 20s
    networks:
     - app-network
    deploy:
      resources:
        limits:
          memory: 1.5GB
      
  backend:
    build:
      context: .
      dockerfile: markdown_note_taking_app.Server/Dockerfile
    ports:
      - "7271:80"
    depends_on:
      sql-server:
        condition: service_healthy
    environment:
      - ConnectionStrings__sqlConnection=Server=sql-server;Database=MarkdownFileDB;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;ConnectRetryCount=5;ConnectRetryInterval=10;
      - ASPNETCORE_ENVIRONMENT=Docker
      - SECRET=YourSuperSecretKeyForDevelopment12345
    networks:
      - app-network
      
  frontend:
    build: ./markdown_note_taking_app.client
    env_file:
      - ./markdown_note_taking_app.client/.env.docker
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sql-data: